services:

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: waap_ai_engine
    ports:
      - "8000:8000"
    volumes:
      - ./ai-service/models:/app/models
      - ./ai-service/data:/app/data
      - ./ai-service/src:/app/src
    networks:
      - waap-net
    restart: always

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: waap_reverse_proxy
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - AI_SERVICE_ENDPOINT=http://ai-service:8000/score
      - WORDPRESS_BACKEND=http://34.53.145.249
      - LISTEN_ADDR=:8080
      - DASHBOARD_ADDR=:9090
      - RISK_THRESHOLD=0.4760
    depends_on:
      - ai-service
    volumes:
      - ./ai-service/data:/app/ai-data
    networks:
      - waap-net
    restart: always

networks:
  waap-net:
    driver: bridge